[package]
name = "reform"
version = "0.1.0"
authors = ["Kenny Flegal <soulstompp@gmail.com>"]
edition = '2018'

[dependencies]
nom = "4.1.1"
time = "0.1.40"
rusqlite = "0.15.0"
postgres = "0.15.2"
mysql = "14.1.1"
chrono = "0.4"
