[package]
name = "sql-composer"
version = "0.1.0"
authors = ["Kenny Flegal <soulstompp@gmail.com>"]
edition = '2018'

[dependencies]
chrono = "0.4"
mysql = "16.0.2"
nom = "4.1.1"
nom_locate = "0.3.1"
rusqlite = "0.17.0"
postgres = "0.15.2"
serde = "1.0.89"
time = "0.1.40"
